name: CI - Build e Deploy de Apps Afetadas (Versão Robusta)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do código
      # fetch-depth: 0 continua sendo crucial.
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Configura o ambiente Node.js e o cache de dependências
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Ou 'yarn', 'pnpm'

      # 3. Instala as dependências
      - name: Install Dependencies
        run: npm ci

      # 4. PASSO CHAVE: Determina as aplicações afetadas e exporta a lista
      - name: Determine Affected Apps
        id: affected-apps # Damos um ID ao passo para referenciar seu output
        run: |
          # 1. Executa o comando do NX para listar APENAS as apps afetadas
          # 2. 'tr' substitui quebras de linha por vírgulas
          # 3. 'sed' remove a última vírgula, se houver
          # 4. 'echo' exporta a string para o output do passo no GitHub Actions
          AFFECTED_LIST=$(npx nx show projects --affected --type=app | tr '\n' ',' | sed 's/,$//')
          echo "lista=${AFFECTED_LIST}" >> $GITHUB_OUTPUT
          echo "Lista de apps afetadas: ${AFFECTED_LIST}"

      # 5. Executa o build para TODOS os projetos afetados (incluindo libs)
      # Isso é importante para garantir que o build da app funcione, pois as libs
      # afetadas precisam ser construídas primeiro.
      - name: Build Affected Projects
        run: npx nx affected -t build --parallel

      # 6. Faz o deploy da API (APENAS SE ELA FOI AFETADA)
      - name: Deploy API
        # A condição 'if' agora verifica a variável 'lista' do passo 'affected-apps'
        if: contains(steps.affected-apps.outputs.lista, 'api')
        run: |
          echo "🚀 Deploying API..."
          # Seu script/comando de deploy aqui
          # Ex: ./scripts/deploy-api.sh

      # 7. Faz o deploy da Web (APENAS SE ELA FOI AFETADA)
      - name: Deploy Web
        if: contains(steps.affected-apps.outputs.lista, 'web')
        run: |
          echo "🚀 Deploying Web App..."
          # Seu script/comando de deploy aqui
